name: material_table_view
description: Flutter library providing a material TableView widget

repository: 'https://github.com/NikolayNIK/material_table_view'

version: 1.0.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

